### ISSUE TITLE
Some Compatability Issues

### ISSUE THREAD

**Issue by iazogu-indeed** [CheesecakeLabs/django-nomad#12]
This is an excellent needed library that would ease development on django projects. We ran into a few issues when installing it. 
1. The print statement does not work on python 2.7 without importing future import. 
2. The folder matching for migration files fails as we have a different project structure from the standard django project structure. Perhaps we can make the regex configurable.

**Comment by smaniotto** [comment]
Hey @iazogu-indeed!
Sorry it took me long to reply, didn't have much time these past days, but I'll resume development soon and can verify these issues. Meanwhile, if you're interested in contributing, happy to review a PR :)

**Comment by smaniotto** [comment]
Hey @iazogu-indeed! I know it's been a long time, not sure if this is still relevant, but the package is fixed for use with Python 2.7!
Thanks for the feedback :)
